# start with  base image containing java runtime

FROM openjdk:8-jdk-alpine

#make port 8989 avaible to the world outside this container 

EXPOSE 8989


COPY target/enrollment-service-1.0-SNAPSHOT.jar  enrollment-service-1.0-SNAPSHOT.jar

